//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_Balashova_.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int MenuItemID { get; set; }
        public string DishesName { get; set; }
        public string Ingredients { get; set; }
        public int Price { get; set; }
        public Nullable<int> CategoryMenuID { get; set; }
        public string Photo { get; set; }
        public int Calories { get; set; }
    
        public virtual CategoryMenu CategoryMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }

        public string ProductImage
        {
            get
            {
                return $"/Resources/{Photo}";
            }
        }





    }
}
