//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_Balashova_.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Balashova_DREntities : DbContext
    {
        private static Balashova_DREntities _context;
        public Balashova_DREntities()
            : base("name=Balashova_DREntities")
        {
        }
        public static Balashova_DREntities GetContext()
        {
            if (_context == null)
                _context = new Balashova_DREntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryMenu> CategoryMenu { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<NomerStolika> NomerStolika { get; set; }
        public virtual DbSet<SostavZakaza> SostavZakaza { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<SposobOplat> SposobOplat { get; set; }
        public virtual DbSet<StatusZakaza> StatusZakaza { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
