//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_Balashova_.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavZakaza
    {
        public int SostavZakazaID { get; set; }
        public int ZakazID { get; set; }
        public int MenuItemID { get; set; }
        public string Kolichestvo { get; set; }
        public decimal Price { get; set; }
    }
}
