//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_Balashova_.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ZakazID { get; set; }
        public Nullable<int> SotrudnikID { get; set; }
        public Nullable<int> MenuItemID { get; set; }
        public string DishesName { get; set; }
        public int Kolichestvo { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusName { get; set; }
        public System.DateTime DataZakaza { get; set; }
        public Nullable<int> SposobOplatID { get; set; }
        public string SposobOplatiName { get; set; }
        public Nullable<int> NomerStolikaID { get; set; }
        public string Nomer { get; set; }
        public Nullable<int> CategoryMenuID { get; set; }
        public Nullable<int> SostavZakazaID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual NomerStolika NomerStolika { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual SposobOplat SposobOplat { get; set; }
        public virtual StatusZakaza StatusZakaza { get; set; }
    }
}
